// Generated by Facebook Swift version 6.3.2-dev (LLVM 89596864ad4cf55, Swift 5a76897d25af804)
#ifndef MWDATCORE_SWIFT_H
#define MWDATCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#elif defined(__OBJC__)
#import <objc/NSObjCRuntime.h>
#import <objc/NSObject.h>
#import <objc/message.h>
#import <objc/objc-api.h>
#import <objc/objc-auto.h>
#import <objc/objc-exception.h>
#import <objc/objc-sync.h>
#import <objc/objc.h>
#import <objc/runtime.h>
#else
#include <objc/NSObjCRuntime.h>
#include <objc/NSObject.h>
#include <objc/message.h>
#include <objc/objc-api.h>
#include <objc/objc-auto.h>
#include <objc/objc-exception.h>
#include <objc/objc-sync.h>
#include <objc/objc.h>
#include <objc/runtime.h>
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface NSNotification (SWIFT_EXTENSION(MWDATCore))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull wearablesRegistrationStateChanged;)
+ (NSNotificationName _Nonnull)wearablesRegistrationStateChanged SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull wearablesDevicesChanged;)
+ (NSNotificationName _Nonnull)wearablesDevicesChanged SWIFT_WARN_UNUSED_RESULT;
@end

/// Errors that can occur when navigating to a screen in the Meta AI companion app.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATNavigationError, "NavigationError", closed) {
/// The Meta AI app is not installed on the device.
  MWDATNavigationErrorMetaAINotInstalled = 0,
/// The app is not registered with AI glasses.
  MWDATNavigationErrorNotRegistered = 1,
};
static NSString * _Nonnull const MWDATNavigationErrorDomain = @"MWDATCore.NavigationError";

SWIFT_CLASS("_TtC9MWDATCore21ObjC_AnyListenerToken")
@interface ObjC_AnyListenerToken : NSObject
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-compatible mirror of <code>Compatibility</code>.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATCompatibility, "ObjC_Compatibility", closed) {
  MWDATCompatibilityUndefined = 0,
  MWDATCompatibilityCompatible = 1,
  MWDATCompatibilityDeviceUpdateRequired = 2,
  MWDATCompatibilitySdkUpdateRequired = 3,
};

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, MWDATLinkState)
SWIFT_CLASS_NAMED("ObjC_Device")
@interface MWDATDevice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (NSString * _Nonnull)nameOrId SWIFT_WARN_UNUSED_RESULT;
/// ObjC-accessible mirror of <code>linkState</code>. Visible from ObjC as <code>linkState</code>.
@property (nonatomic, readonly) enum MWDATLinkState linkState;
/// ObjC-accessible variant of <code>addLinkStateListener(_:)</code>. Visible from ObjC as <code>addLinkStateListener:</code>.
- (ObjC_AnyListenerToken * _Nonnull)addLinkStateListener:(void (^ _Nonnull)(enum MWDATLinkState))listener SWIFT_WARN_UNUSED_RESULT;
/// ObjC-accessible mirror of <code>compatibility()</code>. Visible from ObjC as <code>compatibility</code>.
@property (nonatomic, readonly) enum MWDATCompatibility compatibility;
/// ObjC-accessible variant of <code>addCompatibilityListener(_:)</code>. Visible from ObjC as <code>addCompatibilityListener:</code>.
- (ObjC_AnyListenerToken * _Nonnull)addCompatibilityListener:(void (^ _Nonnull)(enum MWDATCompatibility))listener SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, MWDATDeviceSessionState)
@class NSError;
SWIFT_CLASS_NAMED("ObjC_DeviceSession")
@interface MWDATDeviceSession : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceIdentifier;
/// The current state of this session.
@property (nonatomic, readonly) enum MWDATDeviceSessionState state;
- (void)start:(NSError * _Nullable * _Nullable)error;
- (void)startAndWaitUntilReadyWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)stop;
/// Adds a listener for session state changes.
/// \param listener A block called with the new state value.
///
///
/// returns:
/// A token that must be retained to keep the listener active.
- (ObjC_AnyListenerToken * _Nonnull)addStateListener:(void (^ _Nonnull)(enum MWDATDeviceSessionState))listener SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the current state of a device session.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDeviceSessionState, "ObjC_DeviceSessionState", closed) {
/// The session has been created but not yet started.
  MWDATDeviceSessionStateIdle = 0,
/// The session is connecting to the device.
  MWDATDeviceSessionStateStarting = 1,
/// The session is connected and active.
  MWDATDeviceSessionStateStarted = 2,
/// The session is temporarily paused.
  MWDATDeviceSessionStatePaused = 3,
/// The session is stopping and cleaning up resources.
  MWDATDeviceSessionStateStopping = 4,
/// The session has ended. Create a new session to reconnect.
  MWDATDeviceSessionStateStopped = 5,
};

/// ObjC-compatible mirror of <code>LinkState</code>.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATLinkState, "ObjC_LinkState", closed) {
  MWDATLinkStateDisconnected = 0,
  MWDATLinkStateConnecting = 1,
  MWDATLinkStateConnected = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, MWDATPermission, "ObjC_Permission", closed) {
  MWDATPermissionCamera = 0,
};

typedef SWIFT_ENUM_NAMED(NSInteger, MWDATPermissionStatus, "ObjC_PermissionStatus", closed) {
  MWDATPermissionStatusGranted = 0,
  MWDATPermissionStatusDenied = 1,
};

SWIFT_ENUM_FWD_DECL(NSInteger, MWDATRegistrationState)
@class NSURL;
SWIFT_CLASS_NAMED("ObjC_Wearables")
@interface MWDATWearables : NSObject
+ (void)configure:(NSError * _Nullable * _Nullable)error;
/// Reset the shared state, allowing <code>configure()</code> to be called again.
+ (void)reset;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MWDATWearables * _Nonnull sharedInstance;)
+ (MWDATWearables * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum MWDATRegistrationState registrationState;
- (void)startRegistrationWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)handleUrl:(NSURL * _Nonnull)url completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
- (void)startUnregistrationWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)openFirmwareUpdateWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)openDATGlassesAppUpdateWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull devices;
- (MWDATDevice * _Nullable)deviceForIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT;
- (void)checkPermissionStatus:(enum MWDATPermission)permission completionHandler:(void (^ _Nonnull)(enum MWDATPermissionStatus, NSError * _Nullable))completionHandler;
- (void)requestPermission:(enum MWDATPermission)permission completionHandler:(void (^ _Nonnull)(enum MWDATPermissionStatus, NSError * _Nullable))completionHandler;
- (MWDATDeviceSession * _Nullable)createSessionForDeviceIdentifier:(NSString * _Nonnull)deviceIdentifier error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Errors that can occur during permission requests.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATPermissionError, "PermissionError", open) {
/// No wearable devices have been discovered or registered.
  MWDATPermissionErrorNoDevice = 0,
/// All discovered devices are powered off or disconnected.
  MWDATPermissionErrorNoDeviceWithConnection = 1,
/// A connection error occurred while communicating with the device.
  MWDATPermissionErrorConnectionError = 2,
/// The Meta AI companion app is not installed on the device.
  MWDATPermissionErrorMetaAINotInstalled = 3,
/// A permission request is already in progress.
  MWDATPermissionErrorRequestInProgress = 4,
/// The permission request exceeded the allowed time limit.
  MWDATPermissionErrorRequestTimeout = 5,
/// An unexpected internal error occurred.
  MWDATPermissionErrorInternalError = 6,
};
static NSString * _Nonnull const MWDATPermissionErrorDomain = @"MWDATCore.PermissionError";

/// Error conditions that can occur during the registration process.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATRegistrationError, "RegistrationError", closed) {
/// User is already registered when attempting to register again.
  MWDATRegistrationErrorAlreadyRegistered = 0,
/// The Wearables Device Access Toolkit configuration is invalid or incomplete.
  MWDATRegistrationErrorConfigurationInvalid = 1,
/// The Meta AI app is not installed on the device, which is required for registration.
  MWDATRegistrationErrorMetaAINotInstalled = 2,
/// Network connection is unavailable. Please check your internet connection and try again.
  MWDATRegistrationErrorNetworkUnavailable = 3,
/// The registration process timed out. Please try again.
  MWDATRegistrationErrorTimeout = 4,
/// An unknown error occurred during the registration process.
  MWDATRegistrationErrorUnknown = 5,
};
static NSString * _Nonnull const MWDATRegistrationErrorDomain = @"MWDATCore.RegistrationError";

/// Represents the current state of user registration with the Meta Wearables platform.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATRegistrationState, "RegistrationState", closed) {
/// Registration is not available, typically due to system constraints.
  MWDATRegistrationStateUnavailable = 0,
/// Registration is available and can be initiated.
  MWDATRegistrationStateAvailable = 1,
/// Registration process is in progress.
  MWDATRegistrationStateRegistering = 2,
/// User is successfully registered with the platform.
  MWDATRegistrationStateRegistered = 3,
};

/// Represents the current state of a device session in the Wearables Device Access Toolkit.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATSessionState, "SessionState", closed) {
/// The session is not active and not attempting to connect.
  MWDATSessionStateStopped = 0,
/// The session is waiting for a device to become available for connection.
  MWDATSessionStateWaitingForDevice = 1,
/// The session is actively running and processing data from the device.
  MWDATSessionStateRunning = 2,
/// The session is temporarily paused but maintains its connection.
  MWDATSessionStatePaused = 3,
/// The session state is not currently determinable.
  MWDATSessionStateUnknown = 4,
};

/// Error conditions that can occur during the unregistration process.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATUnregistrationError, "UnregistrationError", closed) {
/// User is already unregistered when attempting to unregister again.
  MWDATUnregistrationErrorAlreadyUnregistered = 0,
/// The Wearables Device Access Toolkit configuration is invalid or incomplete.
  MWDATUnregistrationErrorConfigurationInvalid = 1,
/// The Meta AI app is not installed on the device, which is required for unregistration.
  MWDATUnregistrationErrorMetaAINotInstalled = 2,
/// The registration process timed out. Please try again.
  MWDATUnregistrationErrorTimeout = 3,
/// An unknown error occurred during the unregistration process.
  MWDATUnregistrationErrorUnknown = 4,
};
static NSString * _Nonnull const MWDATUnregistrationErrorDomain = @"MWDATCore.UnregistrationError";

/// Errors that can occur during Device Access Toolkit configuration.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATWearablesError, "WearablesError", closed) {
/// An unexpected internal error occurred during configuration.
  MWDATWearablesErrorInternalError = 0,
/// The Device Access Toolkit has already been configured.
  MWDATWearablesErrorAlreadyConfigured = 1,
/// The configuration provided is invalid or incomplete.
  MWDATWearablesErrorConfigurationError = 2,
};
static NSString * _Nonnull const MWDATWearablesErrorDomain = @"MWDATCore.WearablesError";

/// Errors that can occur during URL handling.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATWearablesHandleURLError, "WearablesHandleURLError", closed) {
/// An unexpected internal error occurred during registration URL handling.
  MWDATWearablesHandleURLErrorRegistrationError = 0,
/// An unexpected internal error occurred during unregistration URL handling.
  MWDATWearablesHandleURLErrorUnregistrationError = 1,
};
static NSString * _Nonnull const MWDATWearablesHandleURLErrorDomain = @"MWDATCore.WearablesHandleURLError";

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
