// Generated by Facebook Swift version 6.3.2-dev (LLVM 89596864ad4cf55, Swift 5a76897d25af804)
#ifndef MWDATCAMERA_SWIFT_H
#define MWDATCAMERA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATCamera",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreMedia;
@import Foundation;
@import MWDATCore;
@import ObjectiveC;
#elif defined(__OBJC__)
#import <CoreMedia/CoreMedia.h>
#import <buck-out/v2/art/fbsource/fbobjc/ios-sdk/MetaWearablesDAT/MWDATCore/__MWDATCore__/ee24224d5d05594a/MWDATCore-Swift.h>
#import <objc/NSObjCRuntime.h>
#import <objc/NSObject.h>
#import <objc/message.h>
#import <objc/objc-api.h>
#import <objc/objc-auto.h>
#import <objc/objc-exception.h>
#import <objc/objc-sync.h>
#import <objc/objc.h>
#import <objc/runtime.h>
#else
#include <CoreMedia/CoreMedia.h>
#include <buck-out/v2/art/fbsource/fbobjc/ios-sdk/MetaWearablesDAT/MWDATCore/__MWDATCore__/ee24224d5d05594a/MWDATCore-Swift.h>
#include <objc/NSObjCRuntime.h>
#include <objc/NSObject.h>
#include <objc/message.h>
#include <objc/objc-api.h>
#include <objc/objc-auto.h>
#include <objc/objc-exception.h>
#include <objc/objc-sync.h>
#include <objc/objc.h>
#include <objc/runtime.h>
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATCamera",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface NSNotification (SWIFT_EXTENSION(MWDATCamera))
/// Posted when stream session state changes.
/// note:
/// Delivered on a background thread. Dispatch to main queue for UI updates.
/// <ul>
///   <li>
///     object: The <code>MWDATStream</code> instance that changed state.
///   </li>
///   <li>
///     userInfo: <code>["state": NSNumber]</code> containing a <code>MWDATStreamState</code> raw value.
///   </li>
/// </ul>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull streamStateChanged;)
+ (NSNotificationName _Nonnull)streamStateChanged SWIFT_WARN_UNUSED_RESULT;
/// Posted when a video frame is received.
/// note:
/// Delivered on a background thread at up to 30-60 fps. Dispatch to main queue for UI updates.
/// <ul>
///   <li>
///     object: The <code>MWDATStream</code> instance that received the frame.
///   </li>
///   <li>
///     userInfo: <code>["frame": MWDATVideoFrame]</code>
///   </li>
/// </ul>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull streamFrameReceived;)
+ (NSNotificationName _Nonnull)streamFrameReceived SWIFT_WARN_UNUSED_RESULT;
/// Posted when a photo is captured.
/// note:
/// Delivered on a background thread. Dispatch to main queue for UI updates.
/// <ul>
///   <li>
///     object: The <code>MWDATStream</code> instance that captured the photo.
///   </li>
///   <li>
///     userInfo: <code>["photo": MWDATPhotoData]</code>
///   </li>
/// </ul>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull streamPhotoCaptured;)
+ (NSNotificationName _Nonnull)streamPhotoCaptured SWIFT_WARN_UNUSED_RESULT;
/// Posted when an error occurs during streaming.
/// note:
/// Delivered on a background thread. Dispatch to main queue for UI updates.
/// <ul>
///   <li>
///     object: The <code>MWDATStream</code> instance where the error occurred.
///   </li>
///   <li>
///     userInfo: <code>["error": NSError]</code> with a <code>localizedDescription</code> suitable for display.
///   </li>
/// </ul>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull streamErrorOccurred;)
+ (NSNotificationName _Nonnull)streamErrorOccurred SWIFT_WARN_UNUSED_RESULT;
@end

/// A device selector that automatically selects the best available device.
/// Selects the first connected device from the devices list.
SWIFT_CLASS_NAMED("ObjC_AutoDeviceSelector")
@interface MWDATAutoDeviceSelector : NSObject
/// Creates an auto device selector that monitors the shared Wearables instance for device changes.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A token that can be used to cancel a listener subscription.
/// Retain this token to keep the listener active; releasing it will cancel the subscription.
SWIFT_CLASS_NAMED("ObjC_CameraListenerToken")
@interface MWDATCameraListenerToken : NSObject
/// Cancels the listener subscription.
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;
@class MWDATStream;
@class MWDATStreamConfiguration;
@interface MWDATDeviceSession (SWIFT_EXTENSION(MWDATCamera))
/// Creates a stream capability with the default configuration.
/// Returns <code>nil</code> without setting <code>error</code> when the device session is not started yet.
- (MWDATStream * _Nullable)addStreamWithError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Creates a stream capability with the provided configuration.
/// Returns <code>nil</code> without setting <code>error</code> when the device session is not started yet.
- (MWDATStream * _Nullable)addStreamWithConfig:(MWDATStreamConfiguration * _Nonnull)config error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

/// Supported formats for capturing photos from Meta Wearables devices.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATPhotoCaptureFormat, "ObjC_PhotoCaptureFormat", closed) {
/// High Efficiency Image Container format (HEIC) - provides better compression than JPEG.
  MWDATPhotoCaptureFormatHeic = 0,
/// Joint Photographic Experts Group format (JPEG) - widely supported image format.
  MWDATPhotoCaptureFormatJpeg = 1,
};

@class NSData;
@class UIImage;
/// A photo captured from a Meta Wearables device.
SWIFT_CLASS_NAMED("ObjC_PhotoData")
@interface MWDATPhotoData : NSObject
/// The photo data in the specified format.
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
/// The format of the captured photo data.
@property (nonatomic, readonly) enum MWDATPhotoCaptureFormat format;
/// Creates a UIImage from the photo data.
///
/// returns:
/// A UIImage, or nil if the data cannot be converted.
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
/// A device selector that always selects a specific, predetermined device.
/// Use this when you want to target operations to a particular device by its identifier.
SWIFT_CLASS_NAMED("ObjC_SpecificDeviceSelector")
@interface MWDATSpecificDeviceSelector : NSObject
/// Creates a device selector that targets a specific device.
/// \param deviceIdentifier The identifier of the device to always select.
///
- (nonnull instancetype)initWithDeviceIdentifier:(NSString * _Nonnull)deviceIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, MWDATStreamState)
@class MWDATVideoFrame;
SWIFT_ENUM_FWD_DECL(NSInteger, MWDATStreamError)
/// A class for managing media streaming sessions with Meta Wearables devices.
/// Handles video streaming, photo capture, and provides real-time state updates.
/// In addition to listener-based callbacks, this class also posts the following notifications:
/// <ul>
///   <li>
///     <code>NSNotification.streamStateChanged</code> - When session state changes
///   </li>
///   <li>
///     <code>NSNotification.streamFrameReceived</code> - When a video frame is received
///   </li>
///   <li>
///     <code>NSNotification.streamPhotoCaptured</code> - When a photo is captured
///   </li>
///   <li>
///     <code>NSNotification.streamErrorOccurred</code> - When an error occurs
///   </li>
/// </ul>
SWIFT_CLASS_NAMED("ObjC_Stream")
@interface MWDATStream : NSObject
/// The configuration used for this streaming session.
@property (nonatomic, readonly, strong) MWDATStreamConfiguration * _Nonnull config;
/// The current state of the streaming session.
@property (nonatomic, readonly) enum MWDATStreamState state;
/// Callback invoked when the session state changes.
/// note:
/// The callback runs on the underlying publisher thread. Dispatch to the main queue
/// before updating UI.
@property (nonatomic, copy) void (^ _Nullable onStateChanged)(enum MWDATStreamState);
/// Callback invoked when a video frame is received.
/// note:
/// The callback runs on the underlying publisher thread and may fire at high frequency.
/// Dispatch to the main queue before updating UI.
@property (nonatomic, copy) void (^ _Nullable onVideoFrame)(MWDATVideoFrame * _Nonnull);
/// Callback invoked when a photo is captured.
/// note:
/// The callback runs on the underlying publisher thread. Dispatch to the main queue
/// before updating UI.
@property (nonatomic, copy) void (^ _Nullable onPhotoData)(MWDATPhotoData * _Nonnull);
/// Callback invoked when a streaming error occurs.
/// note:
/// The callback runs on the underlying publisher thread. Dispatch to the main queue
/// before updating UI.
@property (nonatomic, copy) void (^ _Nullable onError)(enum MWDATStreamError);
/// Starts video streaming from the device.
/// Begins streaming video frames from the currently available device. If no device is currently
/// available, the session enters <code>.waitingForDevice</code> state and automatically connects when a
/// device becomes available.
/// State transitions: <code>.stopped</code> -> <code>.waitingForDevice</code> (no device) or <code>.stopped</code> -> <code>.starting</code>
/// -> <code>.streaming</code> (with device).
- (void)start;
/// Stops video streaming and releases all resources.
/// Shuts down the streaming pipeline and transitions to <code>.stopped</code> state.
/// State transitions: Any state -> <code>.stopping</code> -> <code>.stopped</code>
- (void)stop;
/// Captures a still photo during streaming.
/// Triggers a photo capture while video streaming is active. The captured photo is delivered
/// through the photo data listener. Video streaming is temporarily paused during capture and
/// automatically resumes after photo delivery.
/// \param format The desired image format.
///
///
/// returns:
/// <code>true</code> if the capture request was accepted, <code>false</code> if no device session is
/// active, no high-bandwidth link lease (BTC or WiFi) is held, or a capture is already in
/// progress.
- (BOOL)capturePhotoWithFormat:(enum MWDATPhotoCaptureFormat)format;
/// Adds a listener for state changes.
/// The listener will be called on the underlying publisher thread whenever the session state
/// changes. Dispatch to the main queue before updating UI.
/// \param listener A block called with the new state value.
///
///
/// returns:
/// A token that must be retained to keep the listener active.
- (MWDATCameraListenerToken * _Nonnull)addStateListener:(void (^ _Nonnull)(enum MWDATStreamState))listener SWIFT_WARN_UNUSED_RESULT;
/// Adds a listener for video frames.
/// The listener will be called on the underlying publisher thread for each video frame received.
/// Dispatch to the main queue before updating UI.
/// \param listener A block called with each video frame.
///
///
/// returns:
/// A token that must be retained to keep the listener active.
- (MWDATCameraListenerToken * _Nonnull)addVideoFrameListener:(void (^ _Nonnull)(MWDATVideoFrame * _Nonnull))listener SWIFT_WARN_UNUSED_RESULT;
/// Adds a listener for captured photos.
/// The listener will be called on the underlying publisher thread when a photo is captured.
/// Dispatch to the main queue before updating UI.
/// \param listener A block called with the captured photo data.
///
///
/// returns:
/// A token that must be retained to keep the listener active.
- (MWDATCameraListenerToken * _Nonnull)addPhotoDataListener:(void (^ _Nonnull)(MWDATPhotoData * _Nonnull))listener SWIFT_WARN_UNUSED_RESULT;
/// Adds a listener for errors.
/// The listener will be called on the underlying publisher thread when an error occurs. Dispatch
/// to the main queue before updating UI.
/// \param listener A block called with the error code.
///
///
/// returns:
/// A token that must be retained to keep the listener active.
- (MWDATCameraListenerToken * _Nonnull)addErrorListener:(void (^ _Nonnull)(enum MWDATStreamError))listener SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, MWDATVideoCodec)
SWIFT_ENUM_FWD_DECL(NSInteger, MWDATStreamingResolution)
/// Configuration for a media streaming session with a Meta Wearables device.
SWIFT_CLASS_NAMED("ObjC_StreamConfiguration")
@interface MWDATStreamConfiguration : NSObject
/// The video codec to use for streaming.
@property (nonatomic, readonly) enum MWDATVideoCodec videoCodec;
/// The resolution at which to stream video content.
@property (nonatomic, readonly) enum MWDATStreamingResolution resolution;
/// The target frame rate for the streaming session.
@property (nonatomic, readonly) NSInteger frameRate;
/// Creates a new stream session configuration with default settings.
- (nonnull instancetype)init;
/// Creates a new stream session configuration with specified parameters.
/// \param videoCodec The video codec to use for streaming.
///
/// \param resolution The resolution for video streaming.
///
/// \param frameRate The target frame rate for streaming.
///
- (nonnull instancetype)initWithVideoCodec:(enum MWDATVideoCodec)videoCodec resolution:(enum MWDATStreamingResolution)resolution frameRate:(NSInteger)frameRate OBJC_DESIGNATED_INITIALIZER;
@end

/// Errors that can occur during streaming sessions.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATStreamError, "ObjC_StreamError", closed) {
/// An internal error occurred.
  MWDATStreamErrorInternalError = 0,
/// The specified device could not be found.
  MWDATStreamErrorDeviceNotFound = 1,
/// The specified device is not connected.
  MWDATStreamErrorDeviceNotConnected = 2,
/// The operation timed out.
  MWDATStreamErrorTimeout = 3,
/// Video streaming encountered an error.
  MWDATStreamErrorVideoStreamingError = 4,
/// Camera permission was denied.
  MWDATStreamErrorPermissionDenied = 5,
/// The device hinges were closed during streaming.
  MWDATStreamErrorHingesClosed = 6,
/// The device thermal state has reached a critical level that may affect streaming performance.
  MWDATStreamErrorThermalCritical = 7,
/// The device thermal state has reached an emergency level and the device is shutting down.
  MWDATStreamErrorThermalEmergency = 8,
/// The device has entered peak power shutdown.
  MWDATStreamErrorPeakPowerShutdown = 9,
/// The device battery has reached a critically low level.
  MWDATStreamErrorBatteryCritical = 10,
};

/// Represents the current state of a media streaming session.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATStreamState, "ObjC_StreamState", closed) {
/// The session is completely stopped and not attempting to connect.
  MWDATStreamStateStopped = 0,
/// The session is waiting for a compatible device to become available.
  MWDATStreamStateWaitingForDevice = 1,
/// The session is in the process of starting up.
  MWDATStreamStateStarting = 2,
/// The session is actively streaming media data.
  MWDATStreamStateStreaming = 3,
/// The session is temporarily paused but maintains its connection.
  MWDATStreamStatePaused = 4,
/// The session is in the process of stopping.
  MWDATStreamStateStopping = 5,
};

/// Valid streaming resolutions for live video from Meta Wearables devices.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATStreamingResolution, "ObjC_StreamingResolution", closed) {
/// High resolution streaming at 720x1280 pixels.
  MWDATStreamingResolutionHigh = 0,
/// Medium resolution streaming at 504x896 pixels.
  MWDATStreamingResolutionMedium = 1,
/// Low resolution streaming at 360x640 pixels.
  MWDATStreamingResolutionLow = 2,
};

/// Specifies the video codec to use for streaming.
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATVideoCodec, "ObjC_VideoCodec", closed) {
/// Raw decompressed video frames (420v YUV pixel buffers).
/// Video frames are only delivered while the app is in the foreground.
  MWDATVideoCodecRaw = 0,
/// Compressed HEVC video frames (hvc1).
/// Frames are delivered in both foreground and background.
  MWDATVideoCodecHvc1 = 1,
};

/// Represents a single frame of video data from a Meta Wearables device.
SWIFT_CLASS_NAMED("ObjC_VideoFrame")
@interface MWDATVideoFrame : NSObject
/// Provides access to the underlying video sample buffer.
/// <em>Important</em>: Callers must treat this buffer as read-only. The buffer
/// is only valid for the duration of the listener callback.
@property (nonatomic, readonly) CMSampleBufferRef _Nonnull sampleBuffer;
/// Converts the video frame to a UIImage for display or processing.
///
/// returns:
/// A UIImage representation of the video frame, or nil if conversion fails.
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
